In [2]:
import time
import numpy as np
import matplotlib.pyplot as plt
import dendrogram, linkage


ModuleNotFoundError: No module named 'dendrogram'

In [2]:
tps1 = time.time()

In [3]:
'''
La fonction lire_fasta() est une fonction qui prend en entrée un fichier texte
contenant plusieurs fichiers au format FASTA et stocke
les séquences dans un dictionnaire
'''

'\nLa fonction lire_fasta() est une fonction qui prend en entrée un fichier texte\ncontenant plusieurs fichiers au format FASTA et stocke\nles séquences dans un dictionnaire\n'

In [4]:
def lire_fasta (fichier_fasta):
    '''
    Va retourner un dictionnaire de fichiers au format fasta
    
        Parameters :
            fichier_fasta : fichier texte
        
        Returns :
            prot_dict : un dictionnaire de séquences protéiques au format fasta

    '''
    
    compteur_seq = 0
    prot_dict = {}
    with open(fichier_fasta, "r") as fasta_file:
        prot_id = ""
        for line in fasta_file:
            if line.startswith(">"):
                compteur_seq = compteur_seq +1
                prot_id = compteur_seq
                prot_dict[prot_id] = ""
            else:
                prot_dict[prot_id] += line.strip()
                
    return prot_dict

In [11]:
fasta = lire_fasta('c:/Users/Bismilah/Desktop/M1-IPFB/M2_BI/BQ4CY010/LEBIB_Ines_Projet_Clustal_M2_BI/Fichier_fasta_2.txt')
print("Les séquences protéiques : " , fasta, "\n")

Les séquences protéiques :  {1: 'MALWMRLLPLLALLALWAPAPTRAFVNQHLCGSHLVEALYLVCGERGFFYTPKARREVEDLQVRDVELAGAPGEGGLQPLALEGALQKRGIVEQCCTSICSLYQLENYCN', 2: 'MALWMRFLPLLALLVLWEPKPAQAFVKQHLCGPHLVEALYLVCGERGFFYTPKSRREVEDPQVPQLELGGGPEAGDLQTLALEVARQKRGIVDQCCTSICSLYQLENYCN', 3: 'MNLLCCCCCSNMAPNQRVTRKWELFAGRNKFYCDGLLMSAPHTGVFYLTCILITGTSALFFAFDCPFLADSINPAIPIVGAVLYFFTMSSLLRTTFTDPGVIPRASNDEAAYIEKQIEVNSLNSPTYRPPPRTKEVLVKGQTVKLKYCFTCKIFRPPRASHCSLCDNCVDRFDHHCPWGNCVGKRNYRFFYLFLVSLAFLAVFIFSCSVTHLVLLMKKEHEVFNVIKAAPFTVIVVFICFFSIWSVIGLAGFHTYLTTSDQTTNEDLKGSFSSKGGPRTQNPYSRGNICLNCCHILCGPMTPSLIDRRGIATDEFIQQMQHQSSPRHALSDVLSASHMVTTSQPMMGGLGGGGIGGAGGGISIGGAELKPRFYDESNPSSSTLEGNGGAINGHGNGHGNGFDHPPPSYDLVQNGNSNSLAQLVDNEIPLVQMDIPAYTHQTATQARQYRHRHHKQRQICNGGTVSYENQLANASSEDELDDPDVVVVGSPEVVAAVAAIASNKAREMRNRSGSYSNLFDADFEAALVNSSLADNHVRGEGASSSGKPSAGAALLAAAISGKTENMYSNVLPVDNDTDPADSTLHVYSNIIDERKQQEQANNVLSSTLLCDDLDLDDPVSASCHVKRKSLGDGAEQVKSAERLRMLHDNTMIDTALDLDSLDGSSMGNNSQSCLVKSGKPNATSVTTNVAIV', 4: 'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIA

In [5]:
'''
La fonction lire_blosum62 est une fonction qui permet de lire en entrée
un fichier texte contenant la matrice BLOSUM62 et va
stocker les données de la matrice sous forme de dictionnaire
'''

'\nLa fonction lire_blosum62 est une fonction qui permet de lire en entrée\nun fichier texte contenant la matrice BLOSUM62 et va\nstocker les données de la matrice sous forme de dictionnaire\n'

In [6]:
def lire_blosum62(fichier_blosum):
    
    '''
    Va retourner la matrice BLOSUM62 en dictionnaire
    
        Parameters :
            Fichier texte de la matrice BLOSUM

        
        Returns :
            Dictionnaire de la matrice BLOSUM qui contient tous les scores par pair

    '''
    
    with open(fichier_blosum, 'r') as f:
        lignes = f.readlines()

    new_lines = []
    for line in lignes :
        new_lines.append(line)
    lignes = new_lines

    # Récupère les acides aminés de la première ligne
    # en les splitant pour avoir une liste de string
    acides_amines = lignes[0].split()

    # Crée le dictionnaire BLOSUM62
    blosum62 = {}
    for ligne in lignes[1:]:
        valeurs = ligne.split()
        aa = valeurs[0]
        # Dans le dictionnaire blosum62, la clé contient l'acide aminé aa
        blosum62[aa] = {}
        # on itère sur chaque valeur et on ajoute la valeur correspondante
        # des acides aminés aa et acides_amines[i] dans le dictionnaire
        for i, valeur in enumerate(valeurs[1:]):
            blosum62[aa][acides_amines[i]] = int(valeur)

    return blosum62

In [12]:
blosum62 = lire_blosum62('c:/Users/Bismilah/Desktop/M1-IPFB/M2_BI/BQ4CY010/LEBIB_Ines_Projet_Clustal_M2_BI/Blosum62.txt')
print("Le dictionnaire de la matrice BLOSUM62 : ", blosum62,  "\n")

Le dictionnaire de la matrice BLOSUM62 :  {'A': {'A': 4, 'R': -1, 'N': -2, 'D': -2, 'C': 0, 'Q': -1, 'E': -1, 'G': 0, 'H': -2, 'I': -1, 'L': -1, 'K': -1, 'M': -1, 'F': -2, 'P': -1, 'S': 1, 'T': 0, 'W': -3, 'Y': -2, 'V': 0, 'B': -2, 'J': -1, 'Z': -1, 'X': -1, '*': -4}, 'R': {'A': -1, 'R': 5, 'N': 0, 'D': -2, 'C': -3, 'Q': 1, 'E': 0, 'G': -2, 'H': 0, 'I': -3, 'L': -2, 'K': 2, 'M': -1, 'F': -3, 'P': -2, 'S': -1, 'T': -1, 'W': -3, 'Y': -2, 'V': -3, 'B': -1, 'J': -2, 'Z': 0, 'X': -1, '*': -4}, 'N': {'A': -2, 'R': 0, 'N': 6, 'D': 1, 'C': -3, 'Q': 0, 'E': 0, 'G': 0, 'H': 1, 'I': -3, 'L': -3, 'K': 0, 'M': -2, 'F': -3, 'P': -2, 'S': 1, 'T': 0, 'W': -4, 'Y': -2, 'V': -3, 'B': 4, 'J': -3, 'Z': 0, 'X': -1, '*': -4}, 'D': {'A': -2, 'R': -2, 'N': 1, 'D': 6, 'C': -3, 'Q': 0, 'E': 2, 'G': -1, 'H': -1, 'I': -3, 'L': -4, 'K': -1, 'M': -3, 'F': -3, 'P': -1, 'S': 0, 'T': -1, 'W': -4, 'Y': -3, 'V': -3, 'B': 4, 'J': -3, 'Z': 1, 'X': -1, '*': -4}, 'C': {'A': 0, 'R': -3, 'N': -3, 'D': -3, 'C': 9, 'Q': -3, 'E'

In [14]:
gap = -5
print("La valeur du gap ici vaut : ", gap , "\n")

La valeur du gap ici vaut :  -5 



In [7]:
'''
La fonction score_needleman_wunsch() est une fonction qui permet de calculer le score d'alignement optimal entre deux séquences
Cette fonction se base sur l'algorithme de Needleman-Wunsch. 
Elle prend en entrée deux séquences (pour les alignées),une matrice BLOSUM (ici 62) et une pénalité de gap
'''

"\nLa fonction score_needleman_wunsch() est une fonction qui permet de calculer le score d'alignement optimal entre deux séquences\nCette fonction se base sur l'algorithme de Needleman-Wunsch. \nElle prend en entrée deux séquences (pour les alignées),une matrice BLOSUM (ici 62) et une pénalité de gap\n"

In [8]:
def score_needleman_wunsch(seq1, seq2, blosum62, gap):

    '''
    Va permettre de retourner un score d'alignement optimal entre deux séquences
    
        Parameters :
            seq 1, seq 2 = string de nos séquences
            blosum62 : un dictionnaire de notre matrice BLOSUM62
            gap = un entier, ici il vaut -5
        
        Returns :
            Un score de l'alignement en int

    '''
    
    # Initialisation des variables m, n et scores
    m, n = len(seq1), len(seq2)
    score = []
    score = [[0] * (n + 1) for i in range(m + 1)]

    # Initialisation de la première ligne et première colonne
    # de la matrice des scores avec les pénalités de gap 
    for i in range(m + 1):
        score[i][0] = gap * i
    for j in range(n + 1):
        score[0][j] = gap * j
        
        
    '''
    On calcule le score pour toutes les positions i et j
    (en excluant la première ligne et la première colonne)
    On calcule pour chaque position (i,j) le score que l'on peut
    avoir suivant les cases précédentes et on prend
    le score maximal des trois scores possibles
    '''
    
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            score_match = score[i - 1][j - 1] + blosum62[seq1[i - 1]][seq2[j - 1]]
            score_suppr = score[i - 1][j] + gap
            score_inser = score[i][j - 1] + gap
            score[i][j] = max(score_match, score_suppr, score_inser)
    # On retourne la dernière valeur de la matrice (dernière case en bas à droite)
    return score[m][n]

In [16]:
score = score_needleman_wunsch(fasta[1], fasta[2], blosum62, gap)
print("Score d'alignement entre les séquences :", score , "\n")

Score d'alignement entre les séquences : 466 



In [9]:
'''
La fonction matrice_score() est une fonction qui permet de calculer la matrice des score entre toutes les séquences
contenues dans le fichier FASTA
'''

'\nLa fonction matrice_score() est une fonction qui permet de calculer la matrice des score entre toutes les séquences\ncontenues dans le fichier FASTA\n'

In [10]:
def matrice_score(fichier_fasta) :

    '''
    Va afficher la matrice de score pour chaque paire de séquences
    
        Parameters :
            fichier_fasta = dictionnaire des fichiers fasta
            blosum62 = dictionnaire de la matrice BLOSUM62
            gap = valeur de pénalité, un entier, ici il vaut -5                       

        
        Returns :
            score = un tableau de scores de séquences deux à deux


    '''
    
    n = len(fichier_fasta)
    #On initialise la matrice carré des scores à 0
    score = np.zeros((n,n))
    
    # On itère pour chaque sur toutes les paires de séquences fasta
    # en faisant bien attention de ne pas itérer deux fois
    #le même paire (grâce à 'for j in range(i+1, n)')
    for i in range(n) :
        for j in range(i+1, n) :
            # On appelle la fonction score_needleman_wunsch afin
            # de calculer le score d'alignement de chaque paire
            score[i][j] = score_needleman_wunsch(fichier_fasta[i+1], fichier_fasta[j+1], blosum62, gap)
            # On écrit la matrice de score de maniere symétrique
            score[j][i] = score[i][j]
            
    return score

In [17]:
matrice_des_scores = matrice_score(fasta)
print("La matrice des scores est : \n", matrice_des_scores, "\n")

La matrice des scores est : 
 [[    0.   466. -2449. -2829. -1184. -2036. -2207.  -474.  -163.  -687.]
 [  466.     0. -2444. -2825. -1179. -2035. -2201.  -475.  -161.  -695.]
 [-2449. -2444.     0.  -233.  -680.  -138.  -153. -1498. -1997. -1245.]
 [-2829. -2825.  -233.     0. -1001.  -279.  -283. -1797. -2342. -1543.]
 [-1184. -1179.  -680. -1001.     0.  -397.  -542.  -356.  -750.  -196.]
 [-2036. -2035.  -138.  -279.  -397.     0.   -75. -1074. -1602.  -885.]
 [-2207. -2201.  -153.  -283.  -542.   -75.     0. -1267. -1751.  -990.]
 [ -474.  -475. -1498. -1797.  -356. -1074. -1267.     0.  -158.  -108.]
 [ -163.  -161. -1997. -2342.  -750. -1602. -1751.  -158.     0.  -326.]
 [ -687.  -695. -1245. -1543.  -196.  -885.  -990.  -108.  -326.     0.]] 



In [18]:
'''
La fonction matrice_distance() permet de convertir la matrice de score en matrice de distance. Le but est de ne pas 
avoir de valeurs négatives dans la matrice

Auparavant, les scores les plus élevées signifiaient deux séquences proches.

Avec la matrice des distances, une distance petite, signifie des séquences proches.
'''

'\nLa fonction matrice_distance() permet de convertir la matrice de score en matrice de distance. Le but est de ne pas \navoir de valeurs négatives dans la matrice\n\nAuparavant, les scores les plus élevées signifiaient deux séquences proches.\n\nAvec la matrice des distances, une distance petite, signifie des séquences proches.\n'

In [19]:
def matrice_distance(matrice_score) :

    '''
    Va convertir une matrice de score en matrice de distance
    
        Parameters :
            matrice_score = tableau de scores de séquences deux à deux
        
        Returns :
            matrice_dist = tableau de distances de séquences deux à deux

    '''
    
    n = len(matrice_score)
    #On initialise la matrice carré des scores à 0
    matrice_dist = np.zeros((n,n))
    dist_max = matrice_score.max()
    dist_min = np.min(matrice_score)
    
    for i in range(len(matrice_score)) :
        for j in range(i+1, len(matrice_score)) :
            matrice_dist[i, j] = dist_max - (matrice_score[i,j] + dist_min)
            matrice_dist[j, i] = matrice_dist[i, j]
            
    return matrice_dist

In [20]:
matrice_des_distances = matrice_distance(matrice_des_scores)
print("La matrice des distances est : \n", matrice_des_distances, "\n")

La matrice des distances est : 
 [[   0. 2829. 5744. 6124. 4479. 5331. 5502. 3769. 3458. 3982.]
 [2829.    0. 5739. 6120. 4474. 5330. 5496. 3770. 3456. 3990.]
 [5744. 5739.    0. 3528. 3975. 3433. 3448. 4793. 5292. 4540.]
 [6124. 6120. 3528.    0. 4296. 3574. 3578. 5092. 5637. 4838.]
 [4479. 4474. 3975. 4296.    0. 3692. 3837. 3651. 4045. 3491.]
 [5331. 5330. 3433. 3574. 3692.    0. 3370. 4369. 4897. 4180.]
 [5502. 5496. 3448. 3578. 3837. 3370.    0. 4562. 5046. 4285.]
 [3769. 3770. 4793. 5092. 3651. 4369. 4562.    0. 3453. 3403.]
 [3458. 3456. 5292. 5637. 4045. 4897. 5046. 3453.    0. 3621.]
 [3982. 3990. 4540. 4838. 3491. 4180. 4285. 3403. 3621.    0.]] 



In [22]:
# Pour affichier l'arbre : 
dendro = linkage(matrice_des_distances, method='average')

# Plot du dendrogramme :
plt.figure(figsize=(20, 20))
dendrogram(dendro)
plt.title('Arbre UPGMA')
plt.xlabel('Seq_ID')
plt.ylabel('Distance')
plt.show()

NameError: name 'linkage' is not defined

In [26]:
'''
La fonction ConstruireArbre permet de construire un arbre à partir d'une matrice de distances
Il utilise le principe de construction d'un arbre UPGMA
(Unweighted Pair Group Method with Arithmetic Mean) mais de manière incrémentale
'''

"\nLa fonction ConstruireArbre permet de construire un arbre à partir d'une matrice de distances\nIl utilise le principe de construction d'un arbre UPGMA\n(Unweighted Pair Group Method with Arithmetic Mean) mais de manière incrémentale\n"

In [27]:
def ConstruireArbre(MatriceDistance):
    
    '''
    Va construire un arbre incrémentiel grâce à la méthode UPGMA
    
        Parameters :
            MatriceDistance = tableau de distances de séquences deux à deux
        
        Returns :
            tree = un arbre UPGMA de nos séquences

    '''
    
    n = len(MatriceDistance)
    
    # Initalisation d'une liste de clusters 
    clusters = [[i] for i in range(n)]
    
    distances = MatriceDistance.copy()
    
    while len(clusters) > 1:
        # On cherche les deux clusters les plus proches
        min_distance = float('inf')
        min_indices = (0, 0)
        for i in range(len(clusters)):
            for j in range(i + 1, len(clusters)):
                distance = distances[i][j]
                if distance < min_distance:
                    min_distance = distance
                    min_indices = (i, j)
        # Les coordonnées des deux clusters les plus proches sont stockés dans x et y 
        x, y = min_indices


        # Les deux clusters les plus proches sont fusionnés en un seul cluster
        new_cluster = clusters[x] + clusters[y]
        clusters.append(new_cluster)

        new_distances = [[0] * len(clusters) for i in range(len(clusters))]

        for i in range(len(clusters)):
            for j in range(i + 1, len(clusters)):
                if i < len(distances) and j < len(distances[i]):
                    # Calcul la distance entre les clusters
                    # grâce à une moyenne arithmétique
                    dist = (distances[x][i] + distances[y][j]) / 2
                    new_distances[i][j] = dist
                    new_distances[j][i] = dist
        # On met à jour la matrice des distances
        distances = new_distances
        
        # Les clusteurs les plus proches sont supprimés
        del clusters[max(x, y)]
        del clusters[min(x, y)]
        
    tree = clusters[0]
    for i in range(len(tree)) :
        tree[i] = tree[i]+1
    
    return tree


In [28]:
arbre_UPGMA = ConstruireArbre(matrice_des_distances)
print("L'arbre fréquentiel de nos séquences est : \n ", arbre_UPGMA, "\n")

L'arbre fréquentiel de nos séquences est : 
  [5, 6, 7, 8, 9, 10, 1, 2, 3, 4] 



In [30]:
'''
La fonction alignement_needleman_wunsch() permet de réaliser l'alignement entre deux séquences à l'aide 
de l'algorithme Needleman & Wunsch
'''

"\nLa fonction alignement_needleman_wunsch() permet de réaliser l'alignement entre deux séquences à l'aide \nde l'algorithme Needleman & Wunsch\n"

In [31]:
def alignement_needleman_wunsch(sequences, arbre, blosum62, gap):
    '''
    Va nous permettre de visualiser les alignements entre deux séquences
    
    Parameters:
        sequence: qui sont des séquences issues des fichiers fasta
        arbre : arbre fréquentiel des séquences
        blosum62: dictionnaire de la matrice BLOSUM62
        gap: valeur de pénalité, un entier, ici il vaut -5
        
    Returns:
        Va nous retourner les alignements de séquences
    '''
    
    # On extrait les deux séquences à alignées
    seq1 = fasta[arbre_UPGMA[0]]
    seq2 = fasta[arbre_UPGMA[1]]         

    m = len(seq1)
    n = len(seq2)
    
    score_alignement = [[0] * (n + 1) for i in range(m + 1)]

    for i in range(m + 1):
        score_alignement[i][0] = gap * i
    for j in range(n + 1):
        score_alignement[0][j] = gap * j

    for i in range(1, m + 1):
        for j in range(1, n + 1):
            score_match = score_alignement[i - 1][j - 1] + blosum62[seq1[i - 1]][seq2[j - 1]]
            score_suppr = score_alignement[i - 1][j] + gap
            score_inser = score_alignement[i][j - 1] + gap
            score_alignement[i][j] = max(score_match, score_suppr, score_inser)
            
            
    # Tracement des alignements
    alignment_a, alignment_b = "", ""
    i, j = m, n
    
    while i > 0 and j > 0:
        #On assigne le score de score_alignement suivant la case courante (là où on se situe)
        score_case = score_alignement[i][j]
        score_diag = score_alignement[i - 1][j - 1]
        score_up = score_alignement[i][j - 1]
        score_left = score_alignement[i - 1][j]
        
        ## Ces conditions servent à verifier quel est le score maximal de ces cases ##
        
        # Cas du match de seq1 et seq2 : les deux caractères sont ajoutés dans les
        # deux alignements et on recule en diagonale
        if score_case == score_diag + blosum62[seq1[i - 1]][seq2[j - 1]]:
            alignment_a += seq1[i - 1]
            alignment_b += seq2[j - 1]
            i -= 1
            j -= 1
            
        # Cas de l'insertion/gap dans seq1 :
        # on ajoute le caractère de seq2 dans alignment_b
        # et on insert un gap à alignment_a
        # On passe à la case du haut
        elif score_case == score_up + gap:
            alignment_a += '-'
            alignment_b += seq2[j - 1]
            j -= 1

        # Cas de l'insertion/gap dans seq2 :
        # on ajoute le caractère de seq1 dans alignment_a
        # et on insert un gap à alignment_b
        # On passe à la case de gauche
        
        elif score_case == score_left + gap:
            alignment_a += seq1[i - 1]
            alignment_b += '-'
            i -= 1
            
    # On complète l'alignement jusqu'à ce que i et j atteignent
    # tous les deux 0
    
    while i > 0:
        alignment_a += seq1[i - 1]
        alignment_b += '-'
        i -= 1
    while j > 0:
        alignment_a += '-'
        alignment_b += seq2[j - 1]
        j -= 1

    # Inverse l'ordre pour avoir les bonnes séquences
    alignment_a = alignment_a[::-1]
    alignment_b = alignment_b[::-1]

    return alignment_a, alignment_b

In [32]:
alignement_séquences = alignement_needleman_wunsch(fasta, arbre_UPGMA, blosum62, gap)
print("Alignement des séquences : \n ", alignement_séquences, "\n")

Alignement des séquences : 
  ('MS--PFLYLVLL---VL--GL-----H-ATI-H-CAS-PE----GKVTACHSS--Q--PNATLYKM-SSINADFAFNLYRRFTVETPDKNI--FFSPVSISAALVML-SFG--A-CCSTQ-TEIVETLGFNLTDTP-MVEIQHGFQHLICSLNFPKKELELQIGNALF-IG-KH--L-KP--L--A-KFLNDVKT--LYETE-VFS-T---D-F-SN--ISAAKQEIN-SHVE-M-Q-T-KGKVVGLIQDLKPNT-IM-V--LVNYI-HFKAQWANPFDPSK-TED-S--SSFLID-K-T-TT-VQV----PMMH--Q-M-E-QYYHL-VDM-ELNCTVLQ-MDYSKN-ALA--LFV---LPKEGQME-SVEAAMSSKTLKKWNRLLQK----G-----W-VDL--F---V--PKFSISATYDLGATLLKMGIQHA----YSENA-DFS--GLTE--DN-G-L--K---L--S-------N--AA--HK-AVLH----IGEKGTE--AAA-V---PEVE-LS-DQ---P-E---NTF-LH-PI--I-----QIDRSFML--LIL-E-RST----RSIL-----FLG---KVV---N------P-----T-E--A', 'MKWVTFLLLLFISGSAFSRGVFRREAHKSEIAHRFKDLGEQHFKGLVLIAFSQYLQKCPYEEHIKLVQEV-TDFAKTCVADENAENCDKSIHTLFGD-KLCAIPKLRDNYGELADCCAKQEPERNECFLQHKDDNPNLPPFQRPEAEAMCT-SFQENPTSF-LGHYLHEVARRHPYFYAPELLYYAEKY-NEVLTQCCTESDKAACLTPKLDAVKEKALVAAVRQRMKCSSMQRFGERAFKAWAVARMSQRFPNAEFAEITKLATDVTKINKECCHG-DLLECADDRAELAKYMCENQATISSKLQACCDKPVLQKSQCLAEIEHDNIPADLPSIAADFVEDKEVCKNYA

In [33]:
tps2 = time.time()
print(f"Le temps d'exécution du code pour 10 séquences de 400 acides aminés en moyenne est : {tps2 - tps1:.3} secondes \n")

Le temps d'exécution du code pour 10 séquences de 400 acides aminés en moyenne est : 1.28e+03 secondes 

